name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  dockerfilePath: $(Build.SourcesDirectory)/src/devops-summit/Dockerfile

pr:
- master

stages:
  - stage: Development
    variables:
      - group: DevEnvironment
    jobs:
    - job: ContainerBuild
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: Docker@2
          displayName: Login to ACR
          inputs:
            command: login
            containerRegistry: $(subscription)
        - task: Docker@2
          displayName: Build and push an image to container registry
          inputs:
            command: buildAndPush
            repository: $(containerRepository)
            dockerfile: $(dockerfilePath)
            containerRegistry: $(subscription)
            tags: '$(Build.BuildNumber)'