name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  dockerfilePath: /src/devops-summit

pr:
- master

stages:
  - stage: Development
    variables:
      - group: DevOpsGroup
    jobs:
    - job: Container Build
      steps:
        - task: Docker@2
          displayName: Login to ACR
          inputs:
            command: login
            containerRegistry: devopssydacrsummit2020.azurecr.io
        - task: Docker@2
          displayName: Build and push an image to container registry
          inputs:
            command: buildAndPush
            repository: devopssummit2020
            dockerfile: $(dockerfilePath)
            containerRegistry: devopssydacrsummit2020.azurecr.io
            tags: |
              1