name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  scriptPath: $(Build.SourcesDirectory)\infrastructure\deploy.ps1
  templatePath: $(Build.SourcesDirectory)\infrastructure\template.json
  resourceGroup: "DEVOPS-SYD-ARG-DEMO01"

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - infrastructure/*

stages:
  - stage: Development
    variables:
      - group: DevEnvironment
    jobs:
    - job: InfrastructureDeploy
      pool:
        vmImage: 'windows-latest'
      steps:
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'sp-ado-summit2020'
            action: 'Create Or Update Resource Group'
            resourceGroupName: '$(resourceGroup)'
            location: 'australiaeast'
            templateLocation: 'Linked artifact'
            csmFile: '$(templatePath)'
            deploymentMode: 'Incremental'